### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by dongyun-two** [div-lab/dendromap#3]
Awesome project! and very interesting to see the integration of ML methodology and visualization!

I would like to test it with my custom dataset, but it requires resnet_class predictions and additional information. I wonder how you create 'prediction_results-cifar10-resnet50-test.json'.

Thank you!

**Comment by xnought** [comment]
The data format for that file was pretty arbitrary. 

You can take a look at those files closer, but at the bare minimum you need this information for each image:
```json
{"index": integer, 
"filename": string, 
"features": float[],
"predicted_class": string,
"true_class": string}
```

For the files generated for CIFAR-10 and CIFAR-100 in the [paper](https://arxiv.org/pdf/2205.06935.pdf) we used the features are the flattened output of the second to last or last layer of the resnet to represent each image. So basically generate an array of objects representing each image being pushed through your network and export the results as an array of objects like the one above.

If you take a look at the notebook that generates the clustering files, for example the [CIFAR-10 Resnet50 one](https://github.com/div-lab/dendromap/blob/main/clustering/resnet50_cifar10.ipynb), you'll see that the format of that file doesn't really matter and you just need to get instance level information and the names of the classes for everything to work.

There are some helpful functions in those notebooks that help with adding the prediction information too. Please take a look! I think it will make things more obvious.
